### ISSUE TITLE
Feature for searching comments from all videos on a channel

### ISSUE THREAD

**Issue by pancevac** [pancevac/ytsc-extension#18]
Search comments from all videos on a channel by adding prefix "global:" before searched term
Example: global:some words #

**Comment by aviv926** [comment]
This can be a great option

**Comment by pancevac** [comment]
Implemented in version 1.5.0: [Feature for searching comments on whole channel.](https://github.com/pancevac/ytsc-extension/commit/9670e04145fa60117b517d3b6a95325d61f1eaa6)
