### ISSUE TITLE
ytsc no longer visible in Firefox add-ons site

### ISSUE THREAD

**Issue by allanlaal** [pancevac/ytsc-extension#21]
link no longer works: https://addons.mozilla.org/et/firefox/addon/youtube-comment-search/

**Comment by ttggzz** [comment]
Confirming this as well, thanks for posting. Went to search if there was a keyboard shortcut to close the search pane, then found the dead link as posted above. Also, I severely searched the Mozilla extension list for anything "youtube comment search" related and came up blank.

**Comment by pancevac** [comment]
Fixed.
