### ISSUE TITLE
Allow searching through YouTube community Posts

### ISSUE THREAD

**Issue by GammelSami** [pancevac/ytsc-extension#23]
The extension can only search video comments. But users can also comment on community posts. 

Example post: https://www.youtube.com/post/UgwMGRipZ3DMkicIKlZ4AaABCQ
Same post but different URL because of marked comment: https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw/community?lc=UgxXOA1gOokSSg6rrcd4AaABAg&lb=UgkxRU4nefyPbgVwb5SU0JfADBHrmYTCH1W8

**Comment by pancevac** [comment]
Strange, I was not able to find Youtube API endpoint for searching that resource.
Existing endpoint "commentThreads" does not support searching for post comments.
If you can find docs, please send me or feel free to make PR.
