### ISSUE TITLE
Ups Something went wrong

### ISSUE THREAD

**Issue by SemjonWilke** [pancevac/ytsc-extension#31]
Recently I get "Ups Something went wrong..." on ~~every~~ *certain* videos. Probably a version jump from last time it worked.
Current Firefox Version 100.0.2
Current Addon Version 2.2.0

Already cleared my cache. Problem appears both logged in and logged out from youtube.
Happening right now on this one: https://www.youtube.com/watch?v=80KKEqMCb9Q

EDIT: I just found, that this problem is not at all happening on **every** video as stated before. However, I also could reproduce it on a different computer with the youtube video from above.

**Comment by pancevac** [comment]
Thanks for reporting,  notice that too.
I did some debugging and found out that response object from YouTube API sometimes doesn't have `replies` array, even if `snippet.totalReplyCount` property have int value greater then 0

Debug example:
![Screenshot from 2022-08-18 01-24-26](https://user-images.githubusercontent.com/40486566/185262594-6ad48604-db8e-4a3b-8323-16b93800a128.png)

Fix will be available in the next version.

**Comment by DidierLoiseau** [comment]
Issue is back?

**Comment by ghost** [comment]
> Issue is back?

Do you have a test-video to reproduce it?
